name: remote ssh command

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy commits
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          echo "Remove current version"
          cd /home/${{ secrets.SSH_USERNAME }}
          rm -rf handleYoutubeApi
          echo "Clone Git Repository"
          git clone https://github.com/fjnalta/handleYoutubeApi.git
          echo "Change working directory"
          cd handleYoutubeApi
          echo "Install node modules"
          npm install --save
          echo "Fetch youtube data"
          node index.js